In [1]:
from PIL import Image
import numpy as np
import os
import cv2
import keras
from keras.utils import np_utils
from keras.models import Sequential
from keras.layers import Conv2D,MaxPooling2D,Dense,Flatten,Dropout
from keras.models import model_from_json

Using TensorFlow backend.


In [2]:
data = []
labels = []

inter = os.listdir("C:/Users/Yash Tandon/Desktop/python course/ML projects/frame-classification/dataset/interesting")
for inte in inter:
    img = cv2.imread("C:/Users/Yash Tandon/Desktop/python course/ML projects/frame-classification/dataset/interesting/" + inte)
    print(inte)
    print(img)
    file = Image.fromarray(img, 'RGB')
    rimage = file.resize((50, 50))
    data.append(np.array(rimage))
    labels.append(0)

ninter = os.listdir("C:/Users/Yash Tandon/Desktop/python course/ML projects/frame-classification/dataset/not-interesting")
for ni in ninter:
    img = cv2.imread("C:/Users/Yash Tandon/Desktop/python course/ML projects/frame-classification/dataset/not-interesting/" + ni)
    file = Image.fromarray(img, 'RGB')
    rimage = file.resize((50, 50))
    data.append(np.array(rimage))
    labels.append(1)

027fc81aa26a10b1b907e5f6cadd3a4e.jpeg
[[[128 107  92]
  [129 108  93]
  [129 107  95]
  ...
  [ 73  93  98]
  [ 74  94  99]
  [ 74  94  99]]

 [[129 108  93]
  [129 108  93]
  [129 107  95]
  ...
  [ 79  99 104]
  [ 80 100 105]
  [ 80 100 105]]

 [[128 109  96]
  [129 110  97]
  [128 109  96]
  ...
  [ 83 102 107]
  [ 83 102 107]
  [ 84 103 108]]

 ...

 [[ 83 123 118]
  [ 86 126 121]
  [ 83 123 118]
  ...
  [ 63 110  94]
  [ 63 110  94]
  [ 65 112  96]]

 [[ 96 135 133]
  [ 91 130 128]
  [ 88 127 125]
  ...
  [ 67 112  96]
  [ 70 115  99]
  [ 74 119 103]]

 [[116 155 153]
  [104 143 141]
  [ 96 135 133]
  ...
  [ 71 116 100]
  [ 76 121 105]
  [ 82 127 111]]]
1030-4495546-updates.jpg
[[[113  90  82]
  [115  92  84]
  [122 100  94]
  ...
  [120  85  82]
  [126  93  90]
  [133 100  97]]

 [[114  91  83]
  [114  93  85]
  [122 100  94]
  ...
  [120  87  84]
  [129  96  93]
  [135 104 101]]

 [[115  93  87]
  [114  95  88]
  [120 101  94]
  ...
  [121  92  88]
  [131 102  98]
  [141 112 10

574475-virat-kohli-bowled-twitter.jpg
[[[ 90 133  96]
  [104 147 110]
  [115 159 122]
  ...
  [117 153 117]
  [109 145 109]
  [108 144 108]]

 [[100 143 106]
  [107 150 113]
  [111 155 118]
  ...
  [107 143 107]
  [ 93 129  93]
  [ 81 117  81]]

 [[ 95 138 101]
  [ 96 139 102]
  [ 95 139 102]
  ...
  [ 95 133  97]
  [ 98 136 100]
  [ 97 135  99]]

 ...

 [[110 157 131]
  [101 148 122]
  [ 97 144 118]
  ...
  [103 150 124]
  [105 152 126]
  [106 153 127]]

 [[ 91 138 112]
  [ 94 141 115]
  [100 147 121]
  ...
  [109 156 130]
  [109 156 130]
  [109 156 130]]

 [[104 151 125]
  [109 156 130]
  [110 157 131]
  ...
  [108 155 129]
  [110 157 131]
  [112 159 133]]]
578062-soumya-sarkar-batting-getty.jpg
[[[ 44  57  49]
  [ 45  58  50]
  [ 44  59  51]
  ...
  [238 202 184]
  [237 201 183]
  [236 200 182]]

 [[ 40  53  45]
  [ 43  56  48]
  [ 44  59  51]
  ...
  [238 202 184]
  [237 201 183]
  [236 200 182]]

 [[ 37  50  42]
  [ 41  54  46]
  [ 44  59  51]
  ...
  [238 202 184]
  [237 201 183]

AP-19153141035258-e1565379948534.jpg
[[[51 39 33]
  [17  5  0]
  [36 24 20]
  ...
  [40 27 29]
  [24 11 13]
  [17  4  6]]

 [[46 34 28]
  [22 10  4]
  [41 29 25]
  ...
  [38 25 27]
  [50 37 39]
  [37 24 26]]

 [[47 35 29]
  [32 20 14]
  [42 30 26]
  ...
  [26 13 15]
  [58 45 47]
  [36 23 25]]

 ...

 [[14 17 22]
  [13 16 21]
  [12 15 20]
  ...
  [14 16 17]
  [14 13 15]
  [16 15 17]]

 [[13 13 19]
  [23 23 29]
  [15 15 21]
  ...
  [ 8  7  9]
  [ 3  2  4]
  [ 3  2  4]]

 [[ 0  0  6]
  [19 19 25]
  [11 11 17]
  ...
  [22 21 23]
  [17 16 18]
  [18 17 19]]]
AP19347424793700-0-770x433.jpeg
[[[ 49  42  43]
  [ 49  42  43]
  [ 49  42  43]
  ...
  [ 52  53  71]
  [ 51  53  68]
  [ 49  50  66]]

 [[ 49  42  43]
  [ 49  42  43]
  [ 49  42  43]
  ...
  [ 51  52  70]
  [ 52  54  69]
  [ 51  53  68]]

 [[ 49  42  43]
  [ 49  42  43]
  [ 50  43  44]
  ...
  [ 50  51  67]
  [ 50  51  67]
  [ 50  52  65]]

 ...

 [[ 56 114  89]
  [ 56 114  89]
  [ 56 114  89]
  ...
  [ 56 116  93]
  [ 59 117  94]
  [ 5

cricket-infypune-img-9433.jpg
[[[186 200 218]
  [182 196 214]
  [179 193 211]
  ...
  [ 92 103  93]
  [ 91 105  94]
  [ 91 105  94]]

 [[186 200 218]
  [182 196 214]
  [179 193 211]
  ...
  [ 69  80  70]
  [ 70  84  73]
  [ 72  86  75]]

 [[186 200 218]
  [182 196 214]
  [179 193 211]
  ...
  [ 47  58  50]
  [ 49  62  54]
  [ 52  65  57]]

 ...

 [[ 62 110 122]
  [ 71 119 131]
  [ 82 129 143]
  ...
  [ 70 123 120]
  [ 82 135 132]
  [ 84 138 133]]

 [[ 76 127 129]
  [ 66 117 119]
  [ 53 104 106]
  ...
  [ 48 100 100]
  [ 72 124 124]
  [ 76 129 126]]

 [[ 78 132 119]
  [ 39  93  80]
  [ 57 111  98]
  ...
  [ 43  94  96]
  [ 66 118 118]
  [ 72 124 124]]]
cricket-stumps-stock-photo-csp6370114.jpg
[[[204  96  55]
  [204  96  55]
  [203  95  54]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[206  98  56]
  [205  97  55]
  [205  97  55]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[205 100  57]
  [205 100  57]
  [205 100  57]
  ...
  [255 255 255]
  [255 255 255]
  [2

gettyimages-golovkin-alvarez-boxing-match-cc1e00e2-2aae-4040.jpg
[[[ 10   7   9]
  [ 10   7   9]
  [  9   6   8]
  ...
  [  5   6  10]
  [  3   6  10]
  [  3   6  10]]

 [[ 10   7   9]
  [ 10   7   9]
  [  9   6   8]
  ...
  [  4   6   7]
  [  4   7  11]
  [  4   7  11]]

 [[ 10   7   9]
  [ 10   7   9]
  [ 10   7   9]
  ...
  [  4   3   5]
  [  5   7   8]
  [  6   7  11]]

 ...

 [[184 177 220]
  [178 174 216]
  [173 167 214]
  ...
  [200 129  79]
  [200 127  77]
  [201 125  76]]

 [[192 191 217]
  [186 187 215]
  [182 182 212]
  ...
  [197 126  76]
  [200 127  77]
  [204 128  79]]

 [[190 189 215]
  [187 188 216]
  [187 187 217]
  ...
  [194 123  73]
  [197 124  74]
  [201 125  76]]]
ggg-canelo-41.jpg
[[[  7   5   4]
  [  7   5   4]
  [  7   5   4]
  ...
  [ 14   4   4]
  [ 16   4   4]
  [ 18   6   6]]

 [[  7   5   4]
  [  6   4   3]
  [  7   5   4]
  ...
  [ 14   4   4]
  [ 16   4   4]
  [ 18   6   6]]

 [[  6   4   3]
  [  6   4   3]
  [  7   5   4]
  ...
  [ 16   4   4]
  [ 16   

logan-paul-ksi.jpg
[[[ 15  15  33]
  [ 15  15  33]
  [ 15  15  33]
  ...
  [ 31  29  29]
  [ 31  29  29]
  [ 31  29  29]]

 [[ 16  15  31]
  [ 16  15  31]
  [ 16  15  31]
  ...
  [ 31  29  29]
  [ 31  29  29]
  [ 31  29  29]]

 [[ 15  15  29]
  [ 15  15  29]
  [ 15  15  29]
  ...
  [ 30  28  28]
  [ 31  29  29]
  [ 31  29  29]]

 ...

 [[185 186 230]
  [190 193 238]
  [195 198 243]
  ...
  [ 72  63 149]
  [105  99 180]
  [ 45  40 119]]

 [[184 185 235]
  [191 192 242]
  [194 196 244]
  ...
  [ 19  15  87]
  [ 41  35 116]
  [  9   2  87]]

 [[205 206 255]
  [188 189 240]
  [176 180 229]
  ...
  [  8   7  71]
  [ 29  23 102]
  [ 27  18 108]]]
m-whitlock-of-hornchurch-is-clean-bowled-by-t-savanhu-hornch.jpg
[[[13  8  7]
  [13  8  7]
  [12  7  6]
  ...
  [ 5  4  0]
  [ 5  4  0]
  [ 5  4  0]]

 [[13  8  7]
  [13  8  7]
  [12  7  6]
  ...
  [ 7  6  2]
  [ 7  6  2]
  [ 7  6  2]]

 [[11  7  6]
  [11  7  6]
  [11  7  6]
  ...
  [ 8  7  3]
  [ 8  7  3]
  [ 8  7  3]]

 ...

 [[72 51 50]
  [72 51 

Roy-Story-3-Clean-bowled-again-in-familiar-sequel-still.jpg
[[[160 139 138]
  [150 131 126]
  [146 126 125]
  ...
  [139 115 103]
  [134 110  98]
  [130 110  93]]

 [[159 139 134]
  [149 130 125]
  [143 123 122]
  ...
  [134 113  98]
  [130 110  93]
  [130 110  93]]

 [[153 136 133]
  [147 129 130]
  [142 120 125]
  ...
  [131 111  94]
  [130 109  94]
  [125 106  91]]

 ...

 [[114 123 126]
  [110 118 118]
  [113 124 128]
  ...
  [163 179 192]
  [165 180 196]
  [156 170 188]]

 [[129 137 137]
  [116 122 121]
  [135 142 145]
  ...
  [161 177 189]
  [169 183 201]
  [162 177 193]]

 [[143 148 151]
  [156 161 162]
  [190 194 195]
  ...
  [156 171 187]
  [163 175 193]
  [157 173 190]]]
Ruiz-Joshua-Boxing-JPG-vOhwVO7.jpg
[[[15 13 12]
  [15 13 12]
  [15 13 12]
  ...
  [26 22 21]
  [27 23 22]
  [27 23 22]]

 [[15 13 12]
  [15 13 12]
  [15 13 12]
  ...
  [25 21 20]
  [26 22 21]
  [28 24 23]]

 [[15 13 12]
  [15 13 12]
  [15 13 12]
  ...
  [24 20 19]
  [25 21 20]
  [27 23 22]]

 ...

 [[33 34 55

In [3]:
classifications = np.array(data)
labels = np.array(labels)

np.save('classifications',classifications)
np.save('labels',labels)

s = np.arange(classifications.shape[0])
np.random.shuffle(s)
classifications = classifications[s]
labels = labels[s]

nclasses = len(np.unique(labels))
dlen = len(classifications)

In [4]:
(x_train,x_test)=classifications[(int)(0.1*dlen):],classifications[:(int)(0.1*dlen)]
x_train = x_train.astype('float32')/255
x_test = x_test.astype('float32')/255
train_length=len(x_train)
test_length=len(x_test)

(y_train,y_test)=labels[(int)(0.1*dlen):],labels[:(int)(0.1*dlen)]

y_train=keras.utils.to_categorical(y_train,nclasses)
y_test=keras.utils.to_categorical(y_test,nclasses)
model=Sequential()
model.add(Conv2D(filters=16,kernel_size=2,padding="same",activation="relu",input_shape=(50,50,3)))
model.add(MaxPooling2D(pool_size=2))
model.add(Conv2D(filters=32,kernel_size=2,padding="same",activation="relu"))
model.add(MaxPooling2D(pool_size=2))
model.add(Conv2D(filters=64,kernel_size=2,padding="same",activation="relu"))
model.add(MaxPooling2D(pool_size=2))
model.add(Dropout(0.2))
model.add(Flatten())
model.add(Dense(500,activation="relu"))
model.add(Dropout(0.2))
model.add(Dense(2,activation="softmax"))
model.summary()

Instructions for updating:
Colocations handled automatically by placer.
Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_1 (Conv2D)            (None, 50, 50, 16)        208       
_________________________________________________________________
max_pooling2d_1 (MaxPooling2 (None, 25, 25, 16)        0         
_________________________________________________________________
conv2d_2 (Conv2D)            (None, 25, 25, 32)        2080      
_________________________________________________________________
max_pooling2d_2 (MaxPooling2 (None, 12, 12, 32)        0         
_________________________________________________________________
conv2d_3 (Conv2D)            (None, 12, 12, 64)        8256      
_________________________________________________________________
max_pooling2d_3 (MaxP

In [5]:
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [6]:
model.fit(x_train,y_train,batch_size=50,epochs=100,verbose=1)

Instructions for updating:
Use tf.cast instead.
Epoch 1/100
182/182 [==============================] - 1s 4ms/step - loss: 0.7044 - acc: 0.5330
Epoch 2/100
182/182 [==============================] - 0s 2ms/step - loss: 0.6309 - acc: 0.6484
Epoch 3/100
182/182 [==============================] - 0s 2ms/step - loss: 0.5846 - acc: 0.6978
Epoch 4/100
182/182 [==============================] - 0s 2ms/step - loss: 0.5251 - acc: 0.7637
Epoch 5/100
182/182 [==============================] - 0s 2ms/step - loss: 0.4332 - acc: 0.8462
Epoch 6/100
182/182 [==============================] - 0s 2ms/step - loss: 0.4071 - acc: 0.8462
Epoch 7/100
182/182 [==============================] - 0s 2ms/step - loss: 0.3542 - acc: 0.8626
Epoch 8/100
182/182 [==============================] - 0s 2ms/step - loss: 0.4296 - acc: 0.7912
Epoch 9/100
182/182 [==============================] - 0s 2ms/step - loss: 0.4208 - acc: 0.7967
Epoch 10/100
182/182 [==============================] - 0s 2ms/step - loss: 0.3352 - acc

In [7]:
score = model.evaluate(x_test, y_test, verbose=1)
print('\n', 'Test accuracy:', score[1])

20/20 [==============================] - 0s 3ms/step

 Test accuracy: 0.75


In [9]:
def convert_to_array(img):
    im = cv2.imread(img)
    img = Image.fromarray(im, 'RGB')
    image = img.resize((50, 50))
    return np.array(image)

def get_classification(label):
    if label==0:
        return "interesting"
    if label==1:
        return "not-interesting"
    
def predict_class(file):
    print("Predicting .................................")
    ar=convert_to_array(file)
    ar=ar/255
    label=1
    a=[]
    a.append(ar)
    a=np.array(a)
    score=model.predict(a,verbose=1)
    print(score)
    label_index=np.argmax(score)
    print(label_index)
    acc=np.max(score)
    fclass=get_classification(label_index)
    print(fclass)
    print("The predicted class for the frame is "+fclass+" with accuracy =    "+str(acc))
    
predict_class("1280px-Boxing080905_photoshop.jpg")
predict_class("focused_228979926-stock-photo-portrait-male-female-boxers-standing.jpg")

Predicting .................................
1/1 [==============================] - 0s 2ms/step
[[0.75344294 0.24655698]]
0
interesting
The predicted class for the frame is interesting with accuracy =    0.75344294
Predicting .................................
1/1 [==============================] - 0s 2ms/step
[[0.37201875 0.6279812 ]]
1
not-interesting
The predicted class for the frame is not-interesting with accuracy =    0.6279812
